import pytex
import random
import math
from sys import stderr
class mylist(pytex.ContentList.Itemize):
	_1 = pytex.Block.Center(Content = pytex.Table.Table(
			Rows = 10, 
			Columns = 3, 
			ValueAt = lambda R,C: 
				[R, R*R, math.sqrt(R)][C] if R > 0 
				else [pytex.Block.InlineMath(Content = 'x'),pytex.Block.InlineMath(Content = 'x^2'), pytex.Block.InlineMath(Content = '\sqrt{{x}}')][C]))
	class _2(pytex.ContentList.Itemize):
		_1 = 'Let\'s output an identity matrix'
		#_2 = pytex.Table.Table(Rows = 5, Columns = 5, ValueAt = lambda R,C: int(R==C))
		class _2(pytex.Table.Table):
			Rows = 5
			Columns = 5
			Seperator = ' '
			HSeperator = ''
			def ValueAt(self, R, C): return int(R == C)
		class _3(pytex.ContentList.Enumerate):
			_1 = 'PyTex can use this way to create a latex document'
			_2 = 'And we can also create new filed using program'
			_3 = 'For example, the next 30 line are 10 random number generated by python'
		_4 = r"let's try a plot"
		class _5(pytex.Block.Center):
			class Content(pytex.Plot.TikzAxis):
				_1 = [(x,0.01*x*x) for x in range(-10,10)]
				_2 = [(x,math.sin(x/5.0)) for x in range(-10,10)]
		_6 = r"the next example is a guassian normal distribution"
		_7 = pytex.Block.Center(Content = pytex.Plot.TikzAxis(AxisArgs = '[smooth]'))
obj = mylist()
for i in range(30):
	obj._2._3.push(pytex.TexObject.PlainText(
					"the {idx}-{suf} random number is {rand}",
					idx = i+1, 
					suf = ['st','nd','rd','th'][3 if i > 3 else i], 
					rand = random.random()))
C = {}
D = {}
for i in range(1000000):
	x = round(random.normalvariate(0, 2)*10)
	C[x] = C.get(x,0) +.0001
	x = round(random.normalvariate(0, 3)*10)
	D[x] = D.get(x,0) +.0001
C = C.items()
C.sort()
D = D.items()
D.sort()
obj._2._7._content.addplot(C, '[smooth,blue]')
obj._2._7._content.addplot(D, '[smooth,red]')
print obj
print pytex.Block.InlineMath(r'\sqrt(x)')
