import pytex
import random
from sys import stderr
class mylist(pytex.ContentList.Itemize):
	_1 = pytex.Table.Table(
			Rows = 10, 
			Columns = 2, 
			ValueAt = lambda R,C: 
				[R, R*R][C] if R > 0 
				else [pytex.Block.InlineMath(Content = 'x'),pytex.Block.InlineMath(Content = 'x^2')][C])
	class _2(pytex.ContentList.Itemize):
		_1 = 'Let\'s output an identity matrix'
		#_2 = pytex.Table.Table(Rows = 5, Columns = 5, ValueAt = lambda R,C: int(R==C))
		class _2(pytex.Table.Table):
			Rows = 5
			Columns = 5
			Seperator = ' '
			HSeperator = ''
			def ValueAt(self, R, C): return int(R == C)
		class _3(pytex.ContentList.Enumerate):
			_1 = 'PyTex can use this way to create a latex document'
			_2 = 'And we can also create new filed using program'
			_3 = 'For example, the next 10 line are 10 random number generated by python'
		_4 = r"let's try a plot"
		class _5(pytex.Plot.TikzAxis):
			_1 = [(x,x*x) for x in range(-10,10)]
			_2 = [(x,2*x) for x in range(-10,10)]
obj = mylist()
for i in range(10):
	obj._2._3.push(pytex.TexObject.PlainText("the {idx}-th random number is {rand}",idx = i, rand = random.random()))
print obj
